### ISSUE TITLE
chart sample throwing handler is undefined error

### ISSUE THREAD

**Issue by jgravois** [esridc/citysdk-arcgis#1]
``` javascript
// cedar-core.js (at line 365
// trigger callback
Cedar.prototype.emit = function(eventName) {
  if (this._view._handler._handlers[ eventName ]){
    this._view._handler._handlers[ eventName ][0].handler();
  }
};
>> Uncaught TypeError: Cannot read property 'handler' of undefined  (while eventName is 'update-start')
```

same error visible [here](http://esridc.github.io/citysdk-arcgis/chart.html#)

appears benign, but makes it impossible to step into the code and get an idea of how its working.

**Comment by jgravois** [comment]
ping @ajturner 

now both the `cedar-core.js` and `bubble.json` references in the `chart.html` sample are 404ing.  i can't quite wrap my head around how you are building/serving the template files that i see in `gh-pages` or i would have tried harder to just fix the problem and PR.

@jmeisel thanks for pointing out the problem

**Comment by ajturner** [comment]
There was a refactor of Cedar that didn't propagate to CitySDK. I'll look at it this week - sorry I didn't get to it before the weekend.

**Comment by jgravois** [comment]
no worries.  i'd be more than happy to help propogate things into samples if you don't mind steering me a little.
