### ISSUE TITLE
examples/chart.html bubbles are all too heavy

### ISSUE THREAD

**Issue by jgravois** [esridc/citysdk-arcgis#6]
my fix in #4 displays the chart, but the bubbles are sunk to the bottom of the ocean.  pretty sure we just need to add breaks on the vertical axis.  i'll try and figure out how to do that.

![screenshot 2015-09-17 14 26 07](https://cloud.githubusercontent.com/assets/3011734/9946432/15abbd54-5d48-11e5-84bb-1473b9c132d7.png)

**Comment by jgravois** [comment]
resolved by 5140072 in #4

**Comment by ajturner** [comment]
LGTM!

<img width="1221" alt="citysdk-arcgis" src="https://cloud.githubusercontent.com/assets/1218/10064600/0d099afe-6248-11e5-98e4-0f9d1c5617c6.png">
